import { NextResponse } from 'next/server';

const tasks = [
  "Set a timer for 10 minutes and write or speak everything you're feeling without judgment.",
  "Name three specific things you're grateful for right now.",
  "Pause and complete the sentence: 'Right now, I need...'",
  "Choose one positive 'I am...' statement and repeat it to yourself three times.",
  'Inhale deeply, and as you exhale, visualize releasing one specific worry.',
  'Rate your energy level on a scale of 1-10 without judgment.',
  'Precisely name your current emotion (e.g., melancholic, wistful, content).',
  'Think of a past version of you who was struggling and send her a kind thought.',
  "Text your future self a kind message using a 'scheduled send' app.",
  'Set a 5-minute timer to intensely worry about something, then let it go.',
  'Stretch your entire body for one minute, reaching as far as you can.',
  'Drink a full glass of water mindfully.',
  'Take 10 deep breaths, focusing only on the sensation of breathing.',
  "Wash your hands while feeling the water temperature and the soap's scent.",
  'Stand barefoot on the floor and feel the connection to the ground.',
  'Name one thing you can see, hear, smell, touch, and taste right now.',
  'Slowly roll your shoulders backwards five times, then forwards five times.',
  'Gently tilt your head side to side, holding for a breath on each side.',
  'Take a deep breath in and hum as you exhale long and slow.',
  'Do 20 jumping jacks to get your energy flowing.',
  'Sit quietly and count your breaths up to 10, then start again.',
  'Look out a window and watch the sky for two minutes.',
  'Drink a warm beverage with full attention on the taste and warmth.',
  'Listen to one song you love and do nothing else but listen.',
  'Acknowledge 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste.(ik its stupid but try you might feel good)',
  'Light a candle and watch the flame dance for a minute.',
  'Walk from one room to another, fully aware of each step.',
  'Put your phone in another room for just 5 minutes.',
  'Close your eyes and list every single sound you can hear.',
  'Find an object near you and focus entirely on its texture.',
  'Draw a simple circular pattern and color it in.',
  'Find and photograph one small thing that makes you smile.',
  'Write a 5-7-5 syllable haiku about your day.',
  'Print a free coloring page online and color for 10 minutes.',
  'Create a 3-song playlist for your current mood.',
  'Put on one high-energy song and dance freely.',
  "Look up a 'word of the day' and try to use it.",
  'Give a small space in your room a tiny refresh.',
  'Make a silly face at yourself in the mirror.',
  'Practice designing your signature or a new doodle.',
  "Send a 'thinking of you' text to a friend or family member.",
  'Give a genuine, kind compliment to someone (in person or online).',
  'Send a funny meme to someone who would appreciate it.',
  "Leave a positive comment on a friend's social media post.",
  'Send a quick voice note instead of a text to a close friend.',
  "Text a friend a happy memory: 'Remember when we...?'",
  'Spend 5 minutes petting an animal if you have access.',
  'Water a plant and care for it for a few moments.',
  'Think of someone who helped you and mentally thank them.',
  'Scroll through a few happy memory photos on your phone.',
  'Make your bed to create instant order.',
  'Tidy up the digital workspace on your computer or phone.',
  'Delete 10 old photos from your camera roll.',
  'Unsubscribe from one annoying email mailing list.',
  'Identify the one most important task for today.',
  'Clear off one surface like your nightstand or desk.',
  'Quickly organize one junk drawer.',
  'Return five items to their proper home.',
  'Update one old password for better security.',
  'Empty your bag/wallet and only put back what you need.',
  "Read one article on a topic you're curious about.",
  'Watch the first 10 minutes of an interesting TED Talk.',
  'Google one simple life hack.',
  "Click Wikipedia's 'Random article' and read the first paragraph.",
  'Look up and try one simple new yoga pose.',
  'Listen to the first 10 minutes of a new podcast.',
  "Google 'how to' for something simple you've wondered about.",
  'Practice a tongue twister in your language or another.',
  'Discover one interesting fact to share with others.',
  'Watch a 2-minute nature timelapse video.',
  'Write a single sentence that captures today.',
  'Note the best and most challenging part of your day so far.',
  "Complete the journal prompt: 'If my mood was weather, it would be...'",
  'Write down 3 things you did well recently, no matter how small.',
  'Jot down a fragment of a dream you remember.',
  'Write down 5 random ideas without filtering them.',
  'Write a song lyric that matches your mood and explain why.',
  'List what made you smile today or this week.',
  "Jot down one place you'd like to travel to and why.",
  'Write down one thing you are choosing to release anxiety over.',
  'Step outside for one minute of fresh air.',
  'Stand in a superhero pose (hands on hips) for two minutes.',
  'Mindfully massage hand cream or lotion into your skin.',
  'Splash cool water on your face and wrists.',
  'Make and slowly sip a cup of calming herbal tea.',
  'Set a 5-minute timer and let your mind wander freely.',
  'Lie on the floor for a change of perspective.',
  'Cross your arms and give yourself a firm, comforting squeeze.',
  'Sit in complete silence for just 2 minutes.',
  'Smile for no reason to trigger feel-good hormones.',
  'Save a post or article a friend would like to send them later.',
  'Leave a positive review for a small business or app you like.',
  'Let someone go ahead of you in a line or in traffic.',
  'Donate a small amount online to a cause you care about.',
  'Pick up one piece of litter if you see it safely.',
  'Send a thank you email to a teacher or mentor who influenced you.',
  'Hold the door open for someone with a smile.',
  'Pay a genuine compliment to a customer service worker.',
  'Silently wish a stranger well as they walk by.',
  'Choose one task from this list as an act of kindness for yourself.',
];

export async function POST() {
  const randomIndex = Math.floor(Math.random() * tasks.length);
  const task = tasks[randomIndex];
  return NextResponse.json({ description: task });
}
